// API Routes enum
export enum API_ROUTES {
  GET_PRODUCT_INFO,
  GET_BUILDINGS,
  GET_UNITS,
  SEARCH_STREET,
  POST_USER_REGISTRATION,
  POST_COMPLETE_SALE,
  POST_COMPLETE_LOGIN_SALE,
  LOGIN_USER,
  POST_CHECK_EMAIL,
  GET_POSTAL_CODE,
  GET_NATIONALITY,
  POST_OPERATOR_NAME,
  POST_ORDER_CARD,
  POST_UPLOAD_DOCUMENT,
  POST_BIGIN,
}
export const ROUTES = {
  userDetails: "/pages/UserDetails",
};
