name: Semantic Release

on:
  push:
    branches:
      - main

# Explicitly define permissions
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # This is critical - use the GITHUB_TOKEN to properly authenticate
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Git User
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Semantic Release
        id: semantic
        env:
          # Explicitly pass the token to semantic-release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create .npmrc to configure registry authentication if needed
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN || '' }}" > .npmrc
          
          # Run semantic-release with debug info
          yarn semantic-release --debug
      
      - name: Build if release created
        if: success() && steps.semantic.outcome == 'success'
        run: |
          yarn build
          # Get the latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          
          # Create the archive
          tar -czf "release-${LATEST_TAG}.tar.gz" -C build .
          echo "RELEASE_TAG=${LATEST_TAG}" >> $GITHUB_ENV
      
      - name: Upload build artifact
        if: success() && steps.semantic.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: release-${{ env.RELEASE_TAG }}.tar.gz
          retention-days: 30
